Create CSS structure
ok-technopolis-autumn-2019/Andrey_Matveets pull request #2
Opened 2019-10-16 23:01 UTC by Nekobitlz

Попытался сделать максимально похоже чисто визуально, но так же по пикселям не получилось. Еще у меня не получилось сделать так, чтобы можно было TABом ходить по радио кнопкам (по всем остальным инпутам ходить можно).

2019-10-21 00:17 UTC, fromanywhere requested changes

2019-10-21 00:17 UTC, fromanywhere commented on css/reset.css
> +body,
Хорошо!

2019-10-21 00:17 UTC, fromanywhere commented on css/reset.css
> +    font-size: 14pt;
Оставьте пункты полиграфистам и печатной версии, возьмите пикселы

2019-10-21 00:17 UTC, fromanywhere commented on css/style.css
> +@import "reset.css";
Хорошо!

2019-10-21 00:17 UTC, fromanywhere commented on css/action-bar.css
> +.action-bar {
Не, ну можно не пиксел в пиксел, но не до состояния же, когда макет разлетается 
![image](https://user-images.githubusercontent.com/1042969/67152734-943d7900-f2e5-11e9-9db8-412eadf10761.png)

2019-10-21 00:17 UTC, fromanywhere commented on css/action-bar.css
> +    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
А можно было бы на уровне reset.css один раз определить и больше не думать, оно ж наследуется

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +    border: 1px lightgray solid;
я более чем уверен, что lightgray не эквивалентен макету

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +    .main-controls__select-all {
Методология хорошо!

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +    padding: 16px 18px 17px;
Вот этот паддинг скрадывает активную область контролов, если в него мышкой кликнуть, ничего не произойдет — курсор в поле не поставится, кнопка не нажмется. Уберите его, растяните высоту компонента именно интерактивными элементами, так пользователь будет меньше страдать

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +        overflow: hidden;
выглядит избыточным

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +        overflow: hidden;
шаблон float + overflow принимается, но flow-root был бы уместнее

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +        padding-left: 18px;
у меня вызывает сомнение этот отступ, подарите его лучше активной области какого-нибудь элемента, например, кнопке

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +            flex-grow: 40;
это работать не будет, родитель же не флекс

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +            font-size: xx-large;
такое нужно брать из макета

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +            width: 100%;
Это хорошо, только вот у меня всё прилипло 
![image](https://user-images.githubusercontent.com/1042969/67152843-9eac4280-f2e6-11e9-9e01-21ceb22c1855.png)
Где-то здесь должен быть горизонтальный padding и box-sizing: border-box

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +            width: 100%;
Здесь же видно, что outline на фокусе зарезался overflow, а был бы flow-root, было бы аккуратнее

2019-10-21 00:17 UTC, fromanywhere commented on css/main-controls.css
> +        .main-controls__create-new-input::placeholder {
placeholder — это просто про оформление текста, ему не нужно геометрию описывать, он возьмет её из .main-controls__create-new-input

2019-10-21 00:17 UTC, fromanywhere commented on css/reset.css
> +    background-color: white;
Здесь должна быть строчка из todos.css, а там её быть не должно

2019-10-21 00:17 UTC, fromanywhere commented on css/task-clear-completed.css
> +    float: right;
Либо флоат лишний, либо инлайн-блок

2019-10-21 00:17 UTC, fromanywhere commented on index.html
>                  <button class="task-clear-completed">Clear completed</button>
Дерево поломалось, теперь кнопка лежит в области фильтров и стилизовать её геометрию стало сложно

2019-10-21 00:17 UTC, fromanywhere commented on css/task-counter.css
> +    float:left;
Насколько проще было бы сделать .action-bar флекс-контейнером

2019-10-21 00:17 UTC, fromanywhere commented on css/task-filter.css
> +            visibility:hidden;
а вот был был бы тут position: absolute; left: -9999px;, и не терялась бы навигация

2019-10-21 00:17 UTC, fromanywhere commented on css/task-filter.css
> +            border: solid lightgray 1px;
будет прыгать по горизонтали при выборе разных пунктов. Попробуйте подумать над border: 1px transparent solid и border-color на выбранном элементе

2019-10-21 00:17 UTC, fromanywhere commented on css/task-filter.css
> +    overflow: hidden;
я понимаю, что это попытка выровнять элементы в строку, но как минимум оно зарезает обводку у элементов фильтра (а с flex бы такого не было)

2019-10-21 00:17 UTC, fromanywhere commented on css/task-item.css
> +    clear: both;
Хорошо!

2019-10-21 00:17 UTC, fromanywhere commented on css/task-item.css
> +    align-items: center;
не получится, контейнер-то не флекс

2019-10-21 00:17 UTC, fromanywhere commented on css/task-item.css
> +        overflow: auto;
А зачем overflow?

2019-10-21 00:17 UTC, fromanywhere commented on css/task-item.css
> +        appearance: none;
Хорошо, но аккуратнее с таким, оно экспериментальное, Вам просто повезло, что оно случайно работает в ie тоже

2019-10-21 00:17 UTC, fromanywhere commented on css/task-item.css
> +        border-radius: 100px;
почему 100px, а не, например, 50%?

2019-10-21 00:17 UTC, fromanywhere commented on css/task-item.css
> +            background: url("../icons/completed.png") no-repeat center;
дисплеи с повышенной четкостью здесь страдают, нужно доопределить им графику через media queries

2019-10-21 00:17 UTC, fromanywhere commented on css/task-item.css
> +        flex-grow: 40;
не работает же так, родитель не флекс

2019-10-21 00:17 UTC, fromanywhere commented on css/task-item.css
> +        text-indent: -9999px;
Вообще оно должно появляться только по ховеру (по макету) или по клавиатурному фокусу (по здравому смыслу)

2019-10-21 00:17 UTC, fromanywhere commented on css/title.css
> +        color: inherit;
так оно и без этого унаследуется же

2019-10-21 00:17 UTC, fromanywhere commented on css/todos.css
> +    justify-items: center;
Здесь примерно половина правил нерабочие, если вдуматься

2019-10-21 00:17 UTC, fromanywhere commented on css/todos.css
> +    }
До того, как подгонять пикселы, надо бы разобраться с фундаментальным layoutом. Лучше перечитать что-нибудь по флексбоксам, с флоатами умучаетесь на этом макете — его можно сверстать на флоатах, но там прямо много думать нужно будет по вертикальному выравниванию потом. И, между прочим, crash-test на разрыв пока так себе проходится
![image](https://user-images.githubusercontent.com/1042969/67152965-a28d9400-f2e9-11e9-8fdd-e895e3137d53.png)

Но зато по компонентной структуре прямо в прод можно было бы

2019-10-26 00:18 UTC, Nekobitlz commented
Постарался исправить все замечания, у меня не получилось только сделать иконки через media queries, я так и не смог разобраться с этой штукой, поэтому заменил png иконки на svg из figma.

2019-10-26 15:05 UTC, fromanywhere approved these changes
Тени снизу забыли. Аппрув авансом

2019-10-26 16:38 UTC, merged